"""initial_schema

Revision ID: 45f01e2157f4
Revises: 
Create Date: 2026-04-19 11:13:23.099005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45f01e2157f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_jobs', sa.Column('duration_seconds', sa.Float(), nullable=True))
    op.alter_column('analysis_jobs', 'engine',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'stockfish'::character varying"))
    op.create_index(op.f('ix_analysis_jobs_engine'), 'analysis_jobs', ['engine'], unique=False)
    op.add_column('worker_heartbeats', sa.Column('cpu_model', sa.String(length=256), nullable=True))
    op.add_column('worker_heartbeats', sa.Column('cpu_cores', sa.Integer(), nullable=True))
    op.add_column('worker_heartbeats', sa.Column('memory_mb', sa.Integer(), nullable=True))
    op.add_column('worker_heartbeats', sa.Column('stockfish_binary', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_heartbeats', 'stockfish_binary')
    op.drop_column('worker_heartbeats', 'memory_mb')
    op.drop_column('worker_heartbeats', 'cpu_cores')
    op.drop_column('worker_heartbeats', 'cpu_model')
    op.drop_index(op.f('ix_analysis_jobs_engine'), table_name='analysis_jobs')
    op.alter_column('analysis_jobs', 'engine',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'stockfish'::character varying"))
    op.drop_column('analysis_jobs', 'duration_seconds')
    # ### end Alembic commands ###
