"""add_name_and_email_to_players

Revision ID: 755322e96c64
Revises: b3c9f1a04e87
Create Date: 2026-04-23 19:39:31.043826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755322e96c64'
down_revision: Union[str, Sequence[str], None] = 'b3c9f1a04e87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('players', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_players_email'), 'players', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_email'), table_name='players')
    op.drop_column('players', 'email')
    op.drop_column('players', 'name')
    # ### end Alembic commands ###
