# Generated by Django 6.0.5 on 2026-05-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_add_pv_san_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='claimed_by_key_prefix',
            field=models.CharField(blank=True, help_text='8-char API key prefix of the worker that claimed this job', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='nodes',
            field=models.IntegerField(blank=True, help_text='Lc0 MCTS node budget for this job; null means use LC0_NODES setting', null=True),
        ),
        migrations.AddField(
            model_name='workerheartbeat',
            name='engine',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='workerheartbeat',
            name='status_message',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
